export const endpoints = {
    jadidlar: '/jadidlar',
    jadidlarById: (id) => `/jadidlar/${id}`,
    slayder: '/slayder/',
    slayderById: (id) => `/slayder/${id}/`,
    photos: '/rasmlar/',
    photosById : (id) => `/rasmlar/${id}`,
    videos: '/videolar',
    videosById : (id) => `/videolar/${id}`,
    asarlar: '/asarlar',
    asarlarById: (id) => `/asarlar/${id}`,
    dissertatsiyalar: '/dissertatsiya/',
    dissertatsiyalarById: (id) => `/dissertatsiya/${id}/`,
    maqolalar: '/maqolalar/',
    maqolalarById: (id) => `/maqolalar/${id}/`,
    hotiralar: '/hotiralar/',
    hotiralarById: (id) => `/hotiralar/${id}/`,
    documents: '/arxiv_hujjatlar',
    documentsById: (id) => `/arxiv_hujjatlar/${id}/`,
    hikmatli_sozlar: '/hikmatli_sozlar',
    hikmatli_sozlarById: (id) => `/hikmatli_sozlar/${id}/`,
    foydali_havolalar: '/foydali_havolalar/',
    foydali_havolalarById: (id) => `/foydali_havolalar/${id}/`,
    yangiliklar: '/yangiliklar/',
    yangiliklarById: (id) => `/yangiliklar/${id}/`,
    seminarlar: '/seminarlar/',
    seminarlarById: (id) => `/seminarlar/${id}/`,
    kanfereysiyalar: '/kanferensiyalar/',
    kanfereysiyalarById: (id) => `/kanferensiyalar/${id}/`,
    matbuot : '/matbuotlar/',
    footer: '/tanlovlar/',
    footerById: (id) => `/tanlovlar/${id}/`, 
}